VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 6379, host: 6379
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provision :shell, :path => "provision/shell/provision_prereqs.sh"

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "provision/puppet/manifests"
    puppet.manifest_file = "main.pp"
    puppet.module_path = ["provision/puppet/public_modules", "provision/puppet/private_modules"]
  end

  config.vm.synced_folder "../src", "/home/services/job_reaper"
end
