module.exports = function(sequelize, DataTypes) {
  var Job = sequelize.define('Job', {
    id : {
      type : DataTypes.INTEGER,
      primaryKey : true
    },
    DID : DataTypes.STRING,
    AccountDID : DataTypes.STRING,
    ApplyURL : DataTypes.STRING,
    BeginDate : DataTypes.DATE,
    Categories : DataTypes.STRING,
    CategoriesCodes : DataTypes.STRING,
    ContactInfoFax : DataTypes.STRING,
    ContactInfoName : DataTypes.STRING,
    ContactInfoPhone : DataTypes.STRING,
    ContactInfoEmailURL : DataTypes.STRING,
    CustomApplyType : DataTypes.STRING,
    CompanyDID : DataTypes.STRING,
    CompanyImageURL : DataTypes.STRING,
    CompanyDetailsURL : DataTypes.STRING,
    DisplayJobID : DataTypes.STRING,
    DegreeRequired : DataTypes.STRING,
    DegreeRequiredCode : DataTypes.STRING,
    DescriptionTeaser : DataTypes.TEXT,
    Description : DataTypes.TEXT,
    EmploymentType : DataTypes.STRING,
    EmploymentTypeCode : DataTypes.STRING,
    ExperienceRequired : DataTypes.STRING,
    EndDate : DataTypes.DATE,
    ExternalApplication : DataTypes.BOOLEAN,
    GroupIdentifier: DataTypes.STRING,
    HostSite : DataTypes.STRING,
    IsExpired : DataTypes.BOOLEAN,
    IndustryCodes : DataTypes.STRING,
    JobTitle : DataTypes.TEXT,
    JobDetailsURL : DataTypes.STRING,
    JobModifiedDate : DataTypes.STRING,
    JobServiceURL : DataTypes.STRING,
    Latitude : DataTypes.DECIMAL,
    Location : DataTypes.DECIMAL,
    LocationCity : DataTypes.STRING,
    LocationCountry : DataTypes.STRING,
    LocationFormatted : DataTypes.STRING,
    LocationMetroCity : DataTypes.STRING,
    LocationPostalCode : DataTypes.INTEGER,
    LocationState : DataTypes.STRING,
    LocationStreet1 : DataTypes.STRING,
    LocationStreet2 : DataTypes.STRING,
    Longitude : DataTypes.STRING,
    ONetCode : DataTypes.STRING,
    ONetFriendlyTitle : DataTypes.TEXT,
    Pay : DataTypes.STRING,
    PostedDate : DataTypes.DATE,
    Requirements : DataTypes.TEXT,
    RelocationCovered : DataTypes.BOOLEAN,
    SimilarJobsURL : DataTypes.STRING,
    TNDID : DataTypes.STRING,
    TravelRequired : DataTypes.BOOLEAN,
    TravelRequiredCode : DataTypes.STRING,
    CreatedDate : DataTypes.DATE,
    ModifiedDate : DataTypes.DATE
  },
  {
    timestamps : true,
    updatedAt : "ModifiedDate",
    createdAt : "CreatedDate",
    freezeTableName: true
  });

  return Job;
};
